### ISSUE TITLE
 throw new TypeError('Parameter "url" must be a string, not ' + typeof url);

### ISSUE THREAD

**Issue by harryyuanfeng** [lgraubner/sitemap-generator-cli#13]
hi
when I tried:

sitemap-generator -d http://163.com

it gives me error:

```
url.js:87
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:87:11)
    at urlParse (url.js:81:5)
    at Object.urlResolve [as resolve] (url.js:631:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/sitemap-generator-cli/node_modules/sitemap-generator/lib/SitemapGenerator.js:200:20)
    at /usr/local/lib/node_modules/sitemap-generator-cli/node_modules/cheerio/lib/api/traversing.js:306:18
    at /usr/local/lib/node_modules/sitemap-generator-cli/node_modules/lodash.reduce/index.js:202:9
    at /usr/local/lib/node_modules/sitemap-generator-cli/node_modules/lodash.reduce/index.js:1260:11
    at baseReduce (/usr/local/lib/node_modules/sitemap-generator-cli/node_modules/lodash.reduce/index.js:199:3)
    at Object.reduce (/usr/local/lib/node_modules/sitemap-generator-cli/node_modules/lodash.reduce/index.js:1842:10)
    at initialize.exports.map (/usr/local/lib/node_modules/sitemap-generator-cli/node_modules/cheerio/lib/api/traversing.js:305:23)
```

**Comment by lgraubner** [comment]
I assume the URL-parsing module fails with the number only domain. Will have to investigate further.

**Comment by lgraubner** [comment]
With version 7 it seems not to throw any errors for me. If this error still occurs please open a new issue.
