### ISSUE TITLE
Error: An unknown error occured.

### ISSUE THREAD

**Issue by umbrella-yuri-komarov** [lgraubner/sitemap-generator-cli#23]
`$: sitemap-generator -v http://jellychip.com /root/jellychip.com.xml`

```
[ ADD ] https://www.jellychip.com/
[ ADD ] https://www.jellychip.com/about.html
[ ADD ] https://www.jellychip.com/community.html
[ ADD ] https://www.jellychip.com/help.html
[ ADD ] https://www.jellychip.com/buy.html
[ ADD ] https://www.jellychip.com/get.html
[ ADD ] https://www.jellychip.com/stats.html
[ ADD ] https://www.jellychip.com/terms.html
[ ADD ] https://www.jellychip.com/privacy.html
[ ADD ] https://www.jellychip.com/credits.html
[ ADD ] https://www.jellychip.com/support.html
[ ADD ] https://www.jellychip.com/gifts
[ ADD ] https://www.jellychip.com/news
[ ADD ] https://www.jellychip.com/store/p2/5000
[ ADD ] https://www.jellychip.com/store/p5/12000
[ ADD ] https://www.jellychip.com/store/p6/25000
[ ADD ] https://www.jellychip.com/store/p7/65000
[ ADD ] https://www.jellychip.com/store/p8/140000
[ ADD ] https://www.jellychip.com/store/c1/Featured_Products.html
/usr/lib/node_modules/sitemap-generator-cli/node_modules/sitemap-generator/lib/index.js:101
    throw new Error(message);
    ^

Error: An unknown error occured.
    at Crawler.SitemapGenerator.crawler.on (/usr/lib/node_modules/sitemap-generator-cli/node_modules/sitemap-generator/lib/index.js:101:11)
    at emitTwo (events.js:106:13)
    at Crawler.emit (events.js:191:7)
    at /usr/lib/node_modules/sitemap-generator-cli/node_modules/simplecrawler/lib/crawler.js:1264:25
    at FetchQueue.update (/usr/lib/node_modules/sitemap-generator-cli/node_modules/simplecrawler/lib/queue.js:229:9)
    at ClientRequest.<anonymous> (/usr/lib/node_modules/sitemap-generator-cli/node_modules/simplecrawler/lib/crawler.js:1247:27)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by lgraubner** [comment]
Seems like the SSL cert on this page is invalid. This is now ignored as there is no reason we should care about this (lgraubner/sitemap-generator@b597b98). Watch out for the next bug fix release.

Also gonna adjust the logging to reflect errors like this better.
