### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by shaun-ba** [lgraubner/sitemap-generator-cli#24]
I'm getting a similar error for both sitemap-generator and sitemap-generator-cli.

I'm running node 4.4.2

`/usr/local/lib/node_modules/sitemap-generator-cli/index.js:56
  generator.on('done', ({ added, ignored, errored }) => {
                        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3`

**Comment by lgraubner** [comment]
You need at least Node v6 to use this modules. This is due to new JavaScript Syntax (arrow functions).
